apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: /gitopsfc
  newTag: ee76dc9c56a79ec5830855dbb98be858e8acdcd8
